### ISSUE TITLE
Customize browser dimension

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/puppeteer-screenshot-action#1]
Currently I set it to be 1920x1080. Would be cool to set some inputs to customize the dimensions

```yaml
steps:
  - name: Take photo of github.com
    uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
    with:
      url: https://github.com
      width: 2560
      height: 1440
```

and then grab these fields with `core.getInput`. There's an example of how to do this in the code currently.

**Comment by muhameddelic** [comment]
Hi, I'd be happy to work on this :)

**Comment by lannonbr** [comment]
Sure, Assigned

**Comment by muhameddelic** [comment]
Just an update on this issue.

I've basically completed the work required, but I'd like to ask about testing.
I am new to GitHub actions and after reading some of the documentation about it I was able to confirm that the changes do work using a workflow. I created a separate branch to upload the screenshot to imgur.com so I can see that the width and height params were propagated through to puppeteer.

But, what is your approach to testing actions? I found it a little cumbersome to use a trial and error approach, where I do my changes, tag the commit (1.0.x), update the action.yml to reflect that version and finally seeing the result.

I did look around to see what's out there and came across this https://github.com/nektos/act, would this be something you'd use for local testing?

**Comment by lannonbr** [comment]
Yeah testing GitHub Actions still can be a bit cumbersome as you point out. That said, GitHub is releasing the runners which are the environments your workflows run in on GitHub to be open source platforms sometime this fall, so come late 2019 we hopefully will have the same environment locally and remotely.

For now I do what you commented of doing the back and forth of "testing in production". That said, I would say to make it a bit easier, I believe you can use the branch of your fork so you don't need to keep on updating many files and making continuous tags while testing. It likely would look something like this

```yaml
steps:
  - name: Take photo of github.com
    uses: "muhameddelic/puppeteer-screenshot-action@test-branch"
    with:
      url: https://github.com
```
