### ISSUE TITLE
Not able to see any screenshot in my PR and its showing some error too

### ISSUE THREAD

**Issue by mockey-jockey** [lannonbr/puppeteer-screenshot-action#13]
![image](https://user-images.githubusercontent.com/36475730/91781564-33c2dc00-ec18-11ea-925f-73d0b1acfac7.png)

this my yaml file
```
name: puppeteer
env:
  GITHUB_TOKEN: ********
on:
  push:
    branches: 
      - 'dev'
  pull_request:
    types : [labeled] #adding this as a workaround for  triggering action manually
    branches:
      - 'master'
jobs:
  create_release:
    name: Puppeteer Screenshot Action 
    runs-on: ubuntu-latest
    steps:
      - name: Take photo of github.com
        uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
        with:
          url: https://github.com
          width: 2540
          height: 1440
          fullPage: true
        
```
