### ISSUE TITLE
customize fullpage option

### ISSUE THREAD

**Issue by lannonbr** [lannonbr/puppeteer-screenshot-action#2]
The script grabs a screenshot of the full page. It would be nice to customize this with an input like such:

```yaml
steps:
  - name: Take photo of github.com
    uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
    with:
      url: https://github.com
      fullpage: false
```

and then grab these fields with `core.getInput`. There's an example of how to do this in the code currently.
